2024-05-09 23:51:12,631 INFO    MainThread:27516 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-09 23:51:12,631 INFO    MainThread:27516 [wandb_setup.py:_flush():76] Configure stats pid to 27516
2024-05-09 23:51:12,631 INFO    MainThread:27516 [wandb_setup.py:_flush():76] Loading settings from C:\Users\rahat\.config\wandb\settings
2024-05-09 23:51:12,631 INFO    MainThread:27516 [wandb_setup.py:_flush():76] Loading settings from d:\SEM6\DL\PROJ\BEGIN\wandb\settings
2024-05-09 23:51:12,631 INFO    MainThread:27516 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-09 23:51:12,632 INFO    MainThread:27516 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-09 23:51:12,632 INFO    MainThread:27516 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-09 23:51:12,632 INFO    MainThread:27516 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-09 23:51:12,632 INFO    MainThread:27516 [wandb_init.py:_log_setup():521] Logging user logs to d:\SEM6\DL\PROJ\BEGIN\wandb\run-20240509_235112-yc9oiogl\logs\debug.log
2024-05-09 23:51:12,632 INFO    MainThread:27516 [wandb_init.py:_log_setup():522] Logging internal logs to d:\SEM6\DL\PROJ\BEGIN\wandb\run-20240509_235112-yc9oiogl\logs\debug-internal.log
2024-05-09 23:51:12,633 INFO    MainThread:27516 [wandb_init.py:init():561] calling init triggers
2024-05-09 23:51:12,633 INFO    MainThread:27516 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-05-09 23:51:12,633 INFO    MainThread:27516 [wandb_init.py:init():586] re-initializing run, found existing run on stack: s5ocki0p
2024-05-09 23:51:12,634 INFO    MainThread:27516 [wandb_run.py:_finish():2064] finishing run rebot/wavenet_audio_model/s5ocki0p
2024-05-09 23:51:12,635 ERROR   MainThread:27516 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-05-09 23:51:12,635 INFO    MainThread:27516 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-05-09 23:51:12,635 INFO    MainThread:27516 [wandb_init.py:_jupyter_teardown():449] cleaning up jupyter logic
2024-05-09 23:51:12,635 INFO    MainThread:27516 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-05-09 23:51:12,635 INFO    MainThread:27516 [wandb_run.py:_restore():2287] restore
2024-05-09 23:51:12,636 INFO    MainThread:27516 [wandb_run.py:_restore():2293] restore done
2024-05-09 23:51:19,133 INFO    MainThread:27516 [wandb_init.py:init():611] starting backend
2024-05-09 23:51:19,133 INFO    MainThread:27516 [wandb_init.py:init():615] setting up manager
2024-05-09 23:51:19,134 INFO    MainThread:27516 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-05-09 23:51:19,135 INFO    MainThread:27516 [wandb_init.py:init():623] backend started and connected
2024-05-09 23:51:19,137 INFO    MainThread:27516 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-05-09 23:51:19,137 INFO    MainThread:27516 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-09 23:51:19,137 INFO    MainThread:27516 [wandb_init.py:init():715] updated telemetry
2024-05-09 23:51:19,169 INFO    MainThread:27516 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
